In [ ]:
A - 65
B - 66

CELL -->

JOY, HAPPY

In [ ]:
## Vectors : collection of number :

## [6, 87, 98]  --> vector (Embedding)

## Embedding : Vector representation of text
## Dim of embedding : no. of items in list

In [ ]:
## Types of Embedding :
1) Frequency based :
      -- OHE
      -- Bag-of-words / CountVectorizer
      -- TF-IDF

2) Prediction Based :
      -- Word2Vec
      -- GloVe
      -- FastText


In [ ]:
## Sentiment Analysis :
good, best, awesome    --> Positive
bad, worst, aweful     --> Negative

###One Hot Encoding (OHE) :

In [ ]:
movie is good      --> [movie, is, good]
movie is bad       --> [movie, is, bad]
movie is not good  --> [movie, is, not, good]

vocab = [movie, is, good, bad, not]

movie = [1, 0, 0, 0, 0]
good = [0, 0, 1, 0, 0]
bad = [0, 0, 0, 1, 0]

In [ ]:
1) Tokenization
2) create Vocab
3) create vectores : value of word is 1 else 0

In [ ]:
## Pros :
>> Simple & Intuative

## Cons :
>> Semantic meaning is not captured
>> vector size will increse with increase in vocab size
>> Sparsity :
>> OOV : Out of Vocab

###Bag-of-words / CountVectorizer :

In [ ]:
movie is good      --> [movie, is, good]
movie is bad       --> [movie, is, bad]
movie is not good  --> [movie, is, not, good]

vocab = [movie, is, good, bad, not]

>> movie is good good = [1, 1, 2, 0, 0]
>> movie is bad = [1, 1, 0, 1, 0]
>> movie is not good = [1, 1, 1, 0, 1]

In [49]:
review = [
    "a movie is good good",
    "movie is bad",
    "movie is not good"
    ]
sentiment = [1, 0, 0]

In [56]:
import pandas as pd

df = pd.DataFrame({"review":review, "sentiment":sentiment})
df

review  sentiment
0  a movie is good good          1
1          movie is bad          0
2     movie is not good          0

In [55]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

In [52]:
vectors = cv.fit_transform(df["review"])

In [53]:
vectors[0].toarray()
# movie is good good

array([[0, 2, 1, 1, 0]])

In [54]:
cv.vocabulary_
## {word : index}

{'movie': 3, 'is': 2, 'good': 1, 'bad': 0, 'not': 4}

In [48]:
# movie is bad
vectors[1].toarray()
# [1, 0, 1, 1, 0]

array([[1, 0, 1, 1, 0]])

In [ ]:
# cv = CountVectorizer()
## Hyperparameters :

lowercase : default=True
convert all token in loercase

stop_words : default=None --> "english", list

max_df : default=1.0 --> float, int
float(0.7)  --> Ignore token occuring in more than 70% documnets
int(10)  --> Ignore token occuring in more than 10 documents

min_df : default=1 --> float, int
float(0.1)  --> Ignore token occuring in less than 10% documnets
int(2)  --> Ignore token occuring in less than 2 documents

ngram_range : default=(1,1) --> (min, max)

In [ ]:
## Pros :
>> Simple :
>> Explainability :

## Cons :
>> Semantic meaning is not captured
>> vector size will increse with increase in vocab size
>> Sparsity :
>> OOV : Out of Vocab

###N-Gram :

In [ ]:
This is long movie but not good
This is not long movie but good

In [ ]:
movie is good      --> [movie, is, good]
movie is bad       --> [movie, is, bad]
movie is not good  --> [movie, is, not, good]

vocab = [movie, is, good, bad, not]

In [ ]:
# This is long movie but not good

unigram = [This, is, long, movie, but, not, good]
bigram = [This is, is long, long movie, movie but, but not, not good]
trigram = [This is long, is long movie ...]

In [59]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range=(1, 2))

vectors = cv.fit_transform(df["review"])

In [60]:
cv.vocabulary_

{'movie': 7,
 'is': 3,
 'good': 1,
 'movie is': 8,
 'is good': 5,
 'good good': 2,
 'bad': 0,
 'is bad': 4,
 'not': 9,
 'is not': 6,
 'not good': 10}

In [ ]:
## Pros :
>> Simple :
>> Explainability :
>> Order is also considered at some level

## Cons :
>> Semantic meaning is not captured
>> vector size will increse with increase in vocab size
>> Sparsity :
>> OOV : Out of Vocab

###TF-IDF :

In [ ]:
TF : Term Frequency
IDF : Inverse Document Frequency

In [ ]:
TF = no. of times word occured in doc / total no. of words in doc

IDF = log(total no. of docs / no. of docs containing word)

TF-IDF = TF * IDF

In [ ]:
movie is good      --> [movie, is, good]
movie is bad       --> [movie, is, bad]
movie is not good  --> [movie, is, not, good]

vocab = [movie, is, good, bad, not]

In [ ]:
# movie is good
TF(movie) = 1 / 3
IDF(movie) = log(3 / 3)

TF-IDF(movie) = TF * IDF

In [ ]:
# movie is not good
TF(good) = 1/ 4
IDF(good) = log(3 / 2)

TF-IDF(good) =

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

vectors = tfidf.fit_transform(df["review"])

In [63]:
vectors[0].toarray()

array([[0.        , 0.87653717, 0.34035465, 0.34035465, 0.        ]])

In [64]:
tfidf.get_feature_names_out()

array(['bad', 'good', 'is', 'movie', 'not'], dtype=object)

In [ ]:
## Limitations of Frequency-based Methods :
>> Semantic meaning is not captured
>> vector size will increse with increase in vocab size
>> Sparsity :


In [ ]:
## Use cases for Frequency-based Methods :
>> Information Retriver (Search)
>> Sentiment Analysis :
>> Text Classification :
>> Clustering